name: Generate Snake Contribution Graph

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake Contribution Graph
        uses: Platane/snk@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/github-contribution-grid-snake.svg

      - name: Upload Snake Contribution Graph
        uses: actions/upload-artifact@v2
        with:
          name: snake-graph
          path: dist/github-contribution-grid-snake.svg
